Perfect — you want me to **teach you this entire “Intro: ChatGPT, Transformers, nanoGPT, Shakespeare” lecture** (from Andrej Karpathy’s famous video) in the clear, illustrated, and story-driven **style of Jay Alammar** — who’s known for his visuals and analogies like *“The Illustrated Transformer.”*

Let’s do this step-by-step.

---

## 🧠 1. What Is ChatGPT?

ChatGPT is a **language model** — a neural network trained to predict the next word (or token) in a sequence.
If you give it “Roses are red,” it learns to continue with “violets are blue.”

This is called **language modeling.**
Think of it as autocomplete on steroids: it tries to complete your text, one token at a time.

👉 When you ask ChatGPT to write a poem or answer a question, it doesn’t “look up” answers — it *predicts* plausible continuations based on all the text it’s seen.

---

## 📜 2. Under the Hood: The Transformer

In 2017, Google released the paper **“Attention Is All You Need.”**
It introduced a neural architecture called the **Transformer**, which powers GPT (Generative Pre-trained Transformer).

Transformers changed deep learning because they replaced recurrence (used in RNNs/LSTMs) with a new idea: **attention.**

> Instead of reading words one by one like a tape recorder, the Transformer looks at the whole sentence and *decides which words to pay attention to* when processing each token.

---

## ✍️ 3. Building a Mini-GPT (nanoGPT Style)

To understand how GPT works, Karpathy shows how to train a **tiny Transformer** from scratch — on **Shakespeare’s text**.

### 🧩 Step 1: Get the Data

* All Shakespeare’s works → one big string of ~1 million characters.
* Vocabulary = unique characters (≈ 65 total: letters, spaces, punctuation).
* Each character is mapped to a number (a **token**).

### ⚙️ Step 2: Tokenization

* Turn text → integers.
* Example:

  ```
  "hi!" → [46, 47, 2]
  ```
* In real GPT models, tokenization happens at a *sub-word* level (like “happi” + “ness”), using algorithms like **Byte Pair Encoding (BPE).**

### 🧮 Step 3: Training Data

We split the data into chunks of length N (“block size”).
Each chunk teaches the model:

> Given these N characters, predict the next one.

So the model learns: context → next character.

---

## 🧱 4. The Simplest Language Model: Bigram

Start with a simple baseline — a **bigram model** — which learns only “what letter follows what.”

* If it sees “th,” it learns that “e” often follows.
* No deep context, just local patterns.

Loss ≈ how wrong the model’s predictions are.
Lower loss → better predictions.

---

## 🔄 5. From Bigram to Transformer

Now we want **tokens to talk to each other** — to learn *context.*

That’s where **self-attention** comes in.

---

## 🎯 6. Self-Attention: Let Tokens Talk

Imagine every word (or character) as a node that can “look” at other words to decide what’s relevant.

Each token emits:

* **Query (Q):** “What am I looking for?”
* **Key (K):** “What do I contain?”
* **Value (V):** “What information do I send if you look at me?”

Each token’s *attention score* = dot product between its query and others’ keys.
Then we normalize these scores (softmax) and compute a **weighted average of values**.

👉 This gives each token a *context-aware* representation — it knows which other tokens matter.

---

## 🧩 7. Multi-Headed Attention

One “head” can learn one kind of relationship (like grammar).
Multiple heads learn *different* relationships simultaneously:

* Head 1: who → does what
* Head 2: subject ↔ verb
* Head 3: emotion ↔ tone

All heads run in parallel, then their outputs are concatenated.

---

## 🧮 8. Feed-Forward + Residuals + Layer Norm

After attention, each token processes its new information with a small **feed-forward network** (an MLP).

Then we add:

* **Residual connections** (skip connections) — help gradients flow, avoid vanishing.
* **Layer normalization** — stabilizes training.

Each block ≈ “communicate (attention) → compute (feed-forward).”
Stack many of them → a **Transformer.**

---

## 🧠 9. Scaling Up = GPT

Now scale everything:

* More layers (12 → 96)
* Bigger embeddings (768 → 12 288)
* Larger datasets (1 M tokens → 300 B+)
* Many GPUs

That’s **GPT-3 (175 B parameters)**.

---

## 🪄 10. From Pre-Training to ChatGPT

1. **Pre-training:**
   Learn to predict next token (just like our Shakespeare model) — on a large slice of the internet.

2. **Fine-tuning:**
   Teach the model to act like a helpful assistant.
   Humans write good responses → model learns to imitate.

3. **Reinforcement Learning from Human Feedback (RLHF):**
   Humans rank responses → train a *reward model* → optimize GPT to generate high-reward replies.
   This makes ChatGPT polite, safe, and on-topic.

---

## 🔍 11. Decoder-Only Transformers

* GPT is **decoder-only.**
* Encoder-decoder (original paper) → translation tasks (French → English).
* Decoder-only → text generation.

That’s why GPT models can *generate* new text, not just analyze it.

---

## 🧠 12. nanoGPT Recap

Karpathy’s [nanoGPT](https://github.com/karpathy/nanoGPT):

* ~200 lines of PyTorch code.
* Trains a small GPT on any text (e.g., Shakespeare).
* Demonstrates all components:

  * Token embeddings
  * Positional embeddings
  * Multi-headed self-attention
  * Feed-forward network
  * Residuals + LayerNorm
  * Dropout + Training loop

It’s the **Hello World of Transformers.**

---

## 🌟 13. Key Takeaways

| Concept                   | Role                        |
| ------------------------- | --------------------------- |
| **Tokenization**          | Turn text → numbers         |
| **Attention**             | Let tokens see each other   |
| **Multi-head attention**  | Capture multiple relations  |
| **Feed-forward**          | Compute per-token patterns  |
| **Residual + Layer Norm** | Enable deep training        |
| **Pre-training**          | Learn language structure    |
| **Fine-tuning / RLHF**    | Make it helpful and aligned |

---

## 🏁 Summary (Jay Alammar-Style Wrap-Up)

> 🧩 “Every word looks at every other word, deciding what matters.”
> 🧠 “Stack many such layers, and you get understanding.”
> 💬 “Train it on text, and you get language.”
> 🚀 “Fine-tune it with humans, and you get ChatGPT.”

---

Would you like me to **turn this explanation into a full illustrated guide** (with diagrams, color coding, and analogies like Jay Alammar’s “Attention visualizer”)?
I can generate the visuals next — step by step (e.g., attention heatmaps, architecture blocks, or token flows).


## Building a GPT

Companion notebook to the [Zero To Hero](https://karpathy.ai/zero-to-hero.html) video on GPT.

In [ ]:
# We always start with a dataset to train on. Let's download the tiny shakespeare dataset
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2025-11-04 17:25:07--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   1.06M  --.-KB/s    in 0.07s   

2025-11-04 17:25:07 (14.9 MB/s) - ‘input.txt’ saved [1115394/1115394]



In [ ]:
# read it in to inspect it
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [ ]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  1115394


In [ ]:
# let's look at the first 1000 characters
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [ ]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [ ]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("hii there"))
print(decode(encode("hii there")))

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


In [ ]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

In [ ]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [ ]:
block_size = 8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [ ]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([18]) the target: 47
when input is tensor([18, 47]) the target: 56
when input is tensor([18, 47, 56]) the target: 57
when input is tensor([18, 47, 56, 57]) the target: 58
when input is tensor([18, 47, 56, 57, 58]) the target: 1
when input is tensor([18, 47, 56, 57, 58,  1]) the target: 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]) the target: 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target: 58


In [ ]:
#print(decode(encode("hii there")))
print(decode([47]))

i


In [ ]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
----
when input is [24] the target: 43
when input is [24, 43] the target: 58
when input is [24, 43, 58] the target: 5
when input is [24, 43, 58, 5] the target: 57
when input is [24, 43, 58, 5, 57] the target: 1
when input is [24, 43, 58, 5, 57, 1] the target: 46
when input is [24, 43, 58, 5, 57, 1, 46] the target: 43
when input is [24, 43, 58, 5, 57, 1, 46, 43] the target: 39
when input is [44] the target: 53
when input is [44, 53] the target: 56
when input is [44, 53, 56] the target: 1
when input is [44, 53, 56, 1] the target: 58
when input is [44, 53, 56, 1, 58] the target: 46
when input is [44, 53

In [ ]:
print(xb) # our input to the transformer

tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])


In [ ]:
import torch                          # PyTorch tensor + autograd library
import torch.nn as nn                 # Neural network layers, modules, etc.
from torch.nn import functional as F  # Functional API (losses, activations, etc.)
torch.manual_seed(1337)               # Make randomness reproducible for this run

class BigramLanguageModel(nn.Module):
    """
    A minimal bigram language model:
    - Learns P(next_token | current_token)
    - Uses an embedding table whose rows are tokens and whose columns are logits over tokens.
    """

    def __init__(self, vocab_size):
        super().__init__()  # Initialize nn.Module internals

        # Embedding table: weight shape == (vocab_size, vocab_size)
        # Think of it as a lookup: given a token id t (row index), return a length-vocab vector of logits.
        # Each row 't' encodes logits for "what comes after token t?"
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        """
        idx:      LongTensor of token ids with shape (B, T)
                  B = batch size, T = time steps (sequence length)
        targets:  LongTensor of next-token ids with shape (B, T), optional
        returns:
          logits: FloatTensor of shape (B, T, C) where C = vocab_size
          loss:   Cross-entropy over all (B*T) positions, or None if targets is None
        """

        # 1) Lookup logits for each token in idx:
        #    token_embedding_table does: for every id in idx, return row vector of length vocab_size
        #    idx shape:    (B, T)
        # -> logits shape: (B, T, C)  where C = vocab_size
        logits = self.token_embedding_table(idx)  # (B, T, C)

        if targets is None:
            # If we’re just doing a forward pass for generation, no loss is computed.
            loss = None
        else:
            # Cross-entropy expects 2D logits (N, C) and 1D targets (N)
            # Here N = B*T (flatten all time positions across the batch)

            B, T, C = logits.shape        # Unpack for clarity
            logits = logits.view(B*T, C)  # (B*T, C) -> each row is one time-position’s logits
            targets = targets.view(B*T)   # (B*T,)   -> each entry is the correct next token id

            # Compute average CE loss over all B*T positions
            loss = F.cross_entropy(logits, targets)

        # Return the unflattened logits if targets was None, or flattened logits if it wasn’t.
        # (Most training loops only consume `loss`; logits shape differences usually don’t matter.)
        return logits, loss

    def generate(self, idx, max_new_tokens):
        """
        Autoregressively sample new tokens.

        idx:            LongTensor with shape (B, T_start)
        max_new_tokens: int, how many steps to extend each sequence

        Returns:
            LongTensor of shape (B, T_start + max_new_tokens)
        """
        # Keep appending one token at a time
        for _ in range(max_new_tokens):
            # Forward pass to get next-token logits for every time step in the current context
            # idx shape:   (B, T_now)
            # logits:      (B, T_now, C)
            # loss:        None (no targets during generation)
            logits, loss = self(idx)

            # Focus only on the logits for the last time step:
            # logits[:, -1, :] picks the final T position’s distribution
            # shape becomes: (B, C)
            logits = logits[:, -1, :]  # (B, C)

            # Turn logits into probabilities across the vocabulary
            # probs shape: (B, C)
            probs = F.softmax(logits, dim=-1)

            # Sample one token id per batch element from the categorical distribution
            # idx_next shape: (B, 1)
            idx_next = torch.multinomial(probs, num_samples=1)

            # Concatenate along the time dimension to extend the sequence by 1
            # Before: idx shape (B, T_now)
            # After:  idx shape (B, T_now + 1)
            idx = torch.cat((idx, idx_next), dim=1)

        # After the loop, idx has length T_start + max_new_tokens
        return idx

# ----------------------------
# Example usage (assumes these symbols exist in your environment):
# - vocab_size: int
# - xb: (B, T) LongTensor of input token ids
# - yb: (B, T) LongTensor of target token ids
# - decode: function that maps a list of token ids -> string
# ----------------------------

m = BigramLanguageModel(vocab_size)   # Create model; embedding weight shape (vocab_size, vocab_size)

# Forward pass on a batch:
# xb shape: (B, T), yb shape: (B, T)
# logits shape returned here is (B*T, C) because we computed loss and flattened inside forward
logits, loss = m(xb, yb)

print(logits.shape)  # Expect torch.Size([B*T, C])
print(loss)          # Scalar tensor (e.g., tensor(…)) — average CE over all positions

# Generation demo:
# Start from a single BOS-like token id 0:
# idx start shape: (1, 1)
generated = m.generate(idx=torch.zeros((1, 1), dtype=torch.long),
                       max_new_tokens=100)  # -> (1, 101)

# Convert token ids to text (user-provided `decode`)
print(decode(generated[0].tolist()))

torch.Size([32, 65])
tensor(4.8786, grad_fn=<NllLossBackward0>)

SKIcLT;AcELMoTbvZv C?nq-QE33:CJqkOKH-q;:la!oiywkHjgChzbQ?u!3bLIgwevmyFJGUGp
wnYWmnxKWWev-tDqXErVKLgJ


In [ ]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [ ]:
batch_size = 32
for steps in range(100): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


4.65630578994751


In [ ]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


oTo.JUZ!!zqe!
xBP qbs$Gy'AcOmrLwwt
p$x;Seh-onQbfM?OjKbn'NwUAW -Np3fkz$FVwAUEa-wzWC -wQo-R!v -Mj?,SPiTyZ;o-opr$mOiPJEYD-CfigkzD3p3?zvS;ADz;.y?o,ivCuC'zqHxcVT cHA
rT'Fd,SBMZyOslg!NXeF$sBe,juUzLq?w-wzP-h
ERjjxlgJzPbHxf$ q,q,KCDCU fqBOQT
SV&CW:xSVwZv'DG'NSPypDhKStKzC -$hslxIVzoivnp ,ethA:NCCGoi
tN!ljjP3fwJMwNelgUzzPGJlgihJ!d?q.d
pSPYgCuCJrIFtb
jQXg
pA.P LP,SPJi
DBcuBM:CixjJ$Jzkq,OLf3KLQLMGph$O 3DfiPHnXKuHMlyjxEiyZib3FaHV-oJa!zoc'XSP :CKGUhd?lgCOF$;;DTHZMlvvcmZAm;:iv'MMgO&Ywbc;BLCUd&vZINLIzkuTGZa
D.?


## The mathematical trick in self-attention

In [ ]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [ ]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [ ]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [ ]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

True

In [ ]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


True

In [ ]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [ ]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

Notes:
- Attention is a **communication mechanism**. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other
- In an "encoder" attention block just delete the single line that does masking with `tril`, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides `wei` by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [ ]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [ ]:
k.var()

tensor(1.0449)

In [ ]:
q.var()

tensor(1.0700)

In [ ]:
wei.var()

tensor(1.0918)

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [ ]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [ ]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [ ]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

In [ ]:
# French to English translation example:

# <--------- ENCODE ------------------><--------------- DECODE ----------------->
# les réseaux de neurones sont géniaux! <START> neural networks are awesome!<END>



### Full finished code, for reference

You may want to refer directly to the git repo instead though.

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out





0.209729 M parameters
step 0: train loss 4.4116, val loss 4.4022
step 100: train loss 2.6568, val loss 2.6670
step 200: train loss 2.5090, val loss 2.5058
step 300: train loss 2.4198, val loss 2.4340
step 400: train loss 2.3503, val loss 2.3567
step 500: train loss 2.2970, val loss 2.3136
step 600: train loss 2.2410, val loss 2.2506
step 700: train loss 2.2062, val loss 2.2198
step 800: train loss 2.1638, val loss 2.1871
step 900: train loss 2.1232, val loss 2.1494
step 1000: train loss 2.1020, val loss 2.1293
step 1100: train loss 2.0704, val loss 2.1196
step 1200: train loss 2.0382, val loss 2.0798
step 1300: train loss 2.0249, val loss 2.0640
step 1400: train loss 1.9922, val loss 2.0354
step 1500: train loss 1.9707, val loss 2.0308
step 1600: train loss 1.9614, val loss 2.0474
step 1700: train loss 1.9393, val loss 2.0130
step 1800: train loss 1.9070, val loss 1.9943
step 1900: train loss 1.9057, val loss 1.9871
step 2000: train loss 1.8834, val loss 1.9954
step 2100: train loss 1.

Gotcha — Colab’s text cells can be fussy with LaTeX. Here’s a **LaTeX-free** version that renders cleanly using plain Markdown + monospace blocks (great in Colab). Just paste this into a **Text (Markdown) cell**.

---

# One Attention Head (Causal Self-Attention) — Intuition + Tiny Example (No LaTeX)

**What does a “head” do?**
For each position *t* in a sequence, the head asks: “Which earlier tokens matter to me, and by how much?”
It projects inputs into three spaces—Query (Q), Key (K), and Value (V)—scores relevance with dot products, **masks the future**, softmaxes into probabilities, then blends the Values accordingly.

---

## 1) The three learned lenses

From input embeddings `x` with shape `B × T × n_embd`, we learn three linear projections to `head_size = C`:

* `Q = x · W_Q`
* `K = x · W_K`
* `V = x · W_V`

**Intuition**

* **Query (Q)** = what I’m looking for
* **Key (K)** = what I offer
* **Value (V)** = the content I’ll share if you attend to me

---

## 2) Scoring, masking, and mixing

1. **Affinity scores** (how much token *i* looks at token *j*):

```
scores = (Q @ K^T) / sqrt(C)    # shape: B × T × T
```

2. **Causal mask** (no peeking ahead): set the upper triangle to `-inf` so softmax ignores the future.

3. **Softmax** row-wise:

```
weights = softmax(scores, dim=-1)
```

4. **Weighted sum of values**:

```
out = weights @ V                # shape: B × T × C
```

Dropout (if used) is applied to `weights` during training for regularization.

---

## 3) Tiny worked example (small numbers you can follow)

**Setup**

* Batch `B = 1`, length `T = 3`, head size `C = 2`
* To keep numbers simple, pretend the linear layers are identity (so `Q = K = V = x`)

**Token embeddings**

```
t1 = [1, 0]
t2 = [1, 1]
t3 = [0, 1]
```

### (a) Scores = Q K^T (before scaling)

Dot products:

```
t1⋅t1 = 1    t1⋅t2 = 1    t1⋅t3 = 0
t2⋅t1 = 1    t2⋅t2 = 2    t2⋅t3 = 1
t3⋅t1 = 0    t3⋅t2 = 1    t3⋅t3 = 1
```

Scores matrix:

```
scores =
[ [1, 1, 0],
  [1, 2, 1],
  [0, 1, 1] ]
# (The real code also scales by 1/sqrt(C) to tame magnitudes.)
```

### (b) Causal mask (keep only lower triangle)

```
masked_scores =
[ [1,   -inf, -inf],
  [1,    2,   -inf],
  [0,    1,     1 ] ]
```

### (c) Softmax each row → attention weights

Approximate values:

```
weights ≈
[ [1.000, 0.000, 0.000],
  [0.268, 0.732, 0.000],
  [0.155, 0.422, 0.422] ]
```

### (d) Mix the values (V = x)

```
out = weights @ V
```

Compute row by row:

```
out_t1 = 1.000·t1                           = [1.000, 0.000]
out_t2 = 0.268·t1 + 0.732·t2                = [1.000, 0.732]
out_t3 = 0.155·t1 + 0.422·t2 + 0.422·t3     = [0.577, 0.844]
```

Final `out`:

```
out ≈
[ [1.000, 0.000],
  [1.000, 0.732],
  [0.577, 0.844] ]
```

**Interpretation**

* At `t1`, you can only look at yourself (due to the causal mask).
* At `t2`, you mostly attend to yourself, with a bit of `t1`.
* At `t3`, you blend `t1`, `t2`, and yourself, weighted by learned relevance.

---

## 4) Mapping back to the PyTorch code (line-by-line)

```text
self.key/query/value = nn.Linear(..., bias=False)   # learn K, Q, V projections
self.tril = torch.tril(torch.ones(block_size, block_size))  # lower-tri mask

k = self.key(x); q = self.query(x)                  # shapes: B × T × C
wei = q @ k.transpose(-2, -1) * C**-0.5             # B × T × T similarity scores
wei = wei.masked_fill(self.tril[:T, :T] == 0, -inf) # block "future" positions
wei = F.softmax(wei, dim=-1)                        # row-wise probabilities
wei = self.dropout(wei)                             # regularize during training

v = self.value(x)                                   # B × T × C
out = wei @ v                                       # weighted mix → B × T × C
```

---

## 5) Why this matters

* **Focus:** each token learns *where* to look in the (past) context.
* **Efficiency:** `head_size` is a compact bottleneck.
* **Causality:** triangular mask makes it valid for next-token prediction.

---

### (Optional) Troubleshooting if you *do* want math rendering later

* Make sure you’re in a **Text (Markdown) cell** (not a code cell).
* Colab supports basic LaTeX, but complex environments (`\begin{bmatrix}`) can sometimes be flaky.
* If you re-enable LaTeX, prefer inline like `$x^2$` or block with `$$ ... $$`; avoid fenced code blocks around LaTeX.
* If something still doesn’t render, stick to the ASCII layout above—it's reliable in Colab.


In [ ]:
class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

Awesome—here’s a **Colab-friendly, no-LaTeX** explanation you can paste straight into a Text (Markdown) cell. It matches the style from before and keeps everything in plain Markdown + monospace blocks.

---

# Multi-Head Attention — Many “mini-attentions” in parallel (simple, visual)

**What’s the idea?**
Instead of one attention head, we run **several heads in parallel**.
Each head learns to focus on *different* patterns (syntax, long-range links, punctuation, etc.).
Then we **concatenate** their outputs and use a **linear projection** to mix them back into the model dimension.

---

## The class at a glance

```text
class MultiHeadAttention(nn.Module):
  heads   = [Head(head_size) for _ in range(num_heads)]   # parallel heads
  proj    = nn.Linear(n_embd, n_embd)                     # mix heads together
  dropout = nn.Dropout(dropout)

forward(x):
  out = concat([h(x) for h in heads], dim=-1)  # join along last dim
  out = dropout(proj(out))                     # mix + regularize
  return out
```

* `Head(head_size)` is the same causal self-attention unit you just learned.
* `torch.cat(..., dim=-1)` glues head outputs side-by-side across the **channel** dimension.
* `proj` brings the concatenated vector (size `num_heads * head_size`) back to `n_embd` and lets heads “talk” to each other.
* `dropout` is regularization on the mixed output.

**Shape rule of thumb**

```
Input x:           (B, T, n_embd)
Each head output:  (B, T, head_size)
Concat all heads:  (B, T, num_heads * head_size)  ← should equal n_embd
Projection:        Linear(n_embd → n_embd)
Final:             (B, T, n_embd)
```

---

## Tiny worked example (numbers you can follow)

Let’s make the shapes small and clear:

```
B = 1        # batch size
T = 3        # sequence length
num_heads = 2
head_size = 2
n_embd = num_heads * head_size = 4
```

Assume each `Head` already did its Q/K/V magic and produced these toy outputs:

```
Head 1 output (B,T,C=2):
[
  [ [1.00, 0.00],   # t1
    [1.00, 0.73],   # t2
    [0.58, 0.84] ]  # t3
]

Head 2 output (B,T,C=2):   # imagine this head pays attention differently
[
  [ [0.10, 0.90],   # t1
    [0.40, 0.60],   # t2
    [0.80, 0.20] ]  # t3
]
```

### 1) Concatenate along the last dimension (`dim=-1`)

We glue the per-token vectors from head 1 and head 2 side-by-side:

```
concat = torch.cat([head1, head2], dim=-1)  # shape (B,T,4)

concat =
[
  [ [1.00, 0.00, 0.10, 0.90],   # t1: [h1..., h2...]
    [1.00, 0.73, 0.40, 0.60],   # t2
    [0.58, 0.84, 0.80, 0.20] ]  # t3
]
```

Now each token has a 4-D vector (2 dims per head × 2 heads).

### 2) Mix heads with a projection (`nn.Linear(4, 4)`)

To keep it simple, imagine `proj` is currently an identity-like mapping (so we can see shapes clearly). In a real model, `proj` is learned and can **blend** the head features:

```
out = proj(concat)   # still (B,T,4) but now “heads can talk to each other”
out = dropout(out)   # regularization during training
```

**Intuition:**

* Head 1 might specialize in “who refers to who” (coreference).
* Head 2 might specialize in “nearby collocations” (local patterns).
* `proj` combines these perspectives into one `n_embd`-dim vector per token.

---

## Why multi-heads help

* **Different views:** Each head has its own Q/K/V weights → different attention patterns.
* **Richer features:** Concatenation preserves each head’s unique info before mixing.
* **Controlled capacity:** `num_heads * head_size` is kept equal to `n_embd`, so the model width stays constant.

---

## Mapping back to the code (line-by-line)

```text
self.heads = nn.ModuleList([...])  # store N independent Head modules
self.proj  = nn.Linear(n_embd, n_embd)  # learned mixer across head features
self.dropout = nn.Dropout(dropout)

# Forward:
per_head = [h(x) for h in self.heads]    # N tensors shaped (B,T,head_size)
out = torch.cat(per_head, dim=-1)        # (B,T,num_heads*head_size) == (B,T,n_embd)
out = self.dropout(self.proj(out))       # mix across heads, then regularize
return out
```

---

### Quick sanity checklist (when you wire your own)

* Ensure `n_embd == num_heads * head_size` (so `proj` input matches its in_features).
* Each `Head` should use the same `block_size` mask to keep causality.
* If shapes explode, print: `x.shape`, each `h(x).shape`, the `cat` shape, and `proj.weight.shape`.

That’s it! Paste into Colab and it should read cleanly.


Here’s a clean, Colab-friendly explainer (no LaTeX):

---

# What’s a **bigram language model**?

A **bigram LM** predicts the next token using **only the previous token**.
Formally: “the probability of word *wᵢ* depends only on *wᵢ₋₁*.”

### Tiny example

Training text:
`<BOS> i like pizza <EOS>`
`<BOS> i like pasta <EOS>`
`<BOS> you like pizza <EOS>`

Count adjacent pairs (bigrams):

```
<BOS>→i : 3
i→like  : 2
you→like: 1
like→pizza: 2
like→pasta: 1
pizza→<EOS>: 2
pasta→<EOS>: 1
```

Turn counts into probabilities by normalizing **outgoing** edges:

```
P(i | <BOS>)   = 3 / 3 = 1.0
P(like | i)    = 2 / 2 = 1.0
P(like | you)  = 1 / 1 = 1.0
P(pizza | like)= 2 / 3 ≈ 0.67
P(pasta | like)= 1 / 3 ≈ 0.33
P(<EOS>| pizza)= 2 / 2 = 1.0
P(<EOS>| pasta)= 1 / 1 = 1.0
```

To score a sentence like `<BOS> i like pizza <EOS>`, multiply the bigram probabilities along the path.

> In practice you add **smoothing** (e.g., add-k, Kneser-Ney) so unseen pairs don’t get zero probability.

### Pros / cons

* ✅ Simple, fast, interpretable; great teaching baseline.
* ❌ Short memory (just one token!), can’t capture long-range structure.

---

# Other types of language models

## 1) N-gram (count-based) family

* **Unigram**: next token ignores history entirely (just frequencies).
* **Bigram / Trigram / 4-gram+**: depend on last 1/2/3… tokens.
* **Smoothing & backoff**: Laplace/add-k, **Kneser-Ney**, Katz, interpolated backoff.
* **Caches / interpolations**: mix a global LM with a short-term cache of recent words.

## 2) Early neural LMs

* **Feed-forward NNLM** (Bengio et al., 2003): fixed window of recent tokens → MLP → next-token.
* **Class/factorized softmax**: speedups for huge vocabularies.

## 3) Recurrent models

* **RNN LM**: maintains a hidden state over the whole prefix.
* **LSTM / GRU**: better at long-range dependencies than vanilla RNNs.
* Variants: **char-level** (predict characters), **word/subword-level** (BPE, WordPiece).

## 4) Convolutional LMs

* **CNN LMs** (e.g., gated CNN): use dilated convolutions to capture longer contexts with parallelism.

## 5) Attention-based (Transformers)

* **Causal (autoregressive)**: predict token *t* from tokens `< t`. Examples: GPT-style models; used for generation.
* **Masked (bidirectional)**: fill in masked tokens using both left and right context. Example: BERT (great for understanding/encoding, not pure generation).
* **Seq2Seq (encoder–decoder)**: encode a source sequence, decode a target (e.g., translation, summarization). Examples: T5, BART.
* **Mixture-of-Experts (MoE)**: route tokens to specialized expert subnets for scale.

## 6) Retrieval-augmented & hybrids

* **RAG / RETRO / kNN-LM**: consult an external datastore during prediction to reduce hallucinations and improve factuality.

## 7) Diffusion / energy-based / other researchy LMs

* Alternative training objectives (less common in everyday NLP, active research).

---

# How they differ (at a glance)

```
Memory     | Unigram  Bigram  Trigram  N-gram+  RNN/LSTM/GRU  Transformer
-----------|--------------------------------------------------------------
Context    | none     1 token 2 tokens few tok  long (hidden) long (self-attn)
Parallel   | high     high    high     high     low            high
Generalize | low      low     medium   medium   high           very high
```

---

# Practical notes

* **Tokenization matters**: modern LMs use subwords (BPE/WordPiece) to balance vocab size and OOV handling.
* **Evaluation**: perplexity (lower is better) compares model fit on held-out text.
* **When to use what**: n-grams for tiny data or pedagogy; RNNs if you must be lightweight; Transformers for state-of-the-art performance.

If you want, I can give you a 15-line PyTorch or Python snippet that trains a toy **bigram** model on a tiny corpus and prints its probabilities.


In [ ]:
class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))
